org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1

mod_id=enchanter_letter
mod_name=\u9b54\u6cd5\u624b\u672d
mod_license=All Rights Reserved
mod_version=2.0.0

maven_group=cn.autoforged.enchanter_letter
archives_base_name=enchanter_letter

loader_version=0.16.10
fabric_version=0.110.0+1.21.1
